# Generated by Django 4.2.2 on 2023-06-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgentID', models.CharField(max_length=50)),
                ('Queue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueID', models.CharField(max_length=50)),
                ('userID', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('problem', models.TextField()),
                ('time', models.TimeField()),
                ('Status', models.CharField(choices=[('INQUEUE', 'INQUEUE'), ('ASSIGNED', 'ASSIGNED'), ('DISPATCHED', 'DISPATCHED')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanicID', models.CharField(max_length=50)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
